# Generated by Django 3.1.3 on 2020-11-20 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bulbasaur', 'Bulbasaur'), ('charmander', 'Charmander'), ('squirtle', 'Squirtle'), ('unknown', 'unknown')], default='unknown', max_length=50)),
                ('first_type', models.CharField(choices=[('electric', 'Electric'), ('fire', 'Fire'), ('grass', 'Grass'), ('water', 'Water'), ('unknown', 'unknown')], default='unknown', max_length=50)),
                ('second_type', models.CharField(blank=True, choices=[('ground', 'Ground'), ('flying', 'Flying'), ('poison', 'Poison'), ('unknown', 'unknown')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.species')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='trainer.trainer')),
            ],
        ),
    ]
